# fly.toml app configuration file generated for blog-api-gabe-ess-divine-moon-590 on 2024-01-14T12:59:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-api-gabe-ess-divine-moon-590"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
